# description: Where to import from
# type: string
# required: true
src: TODO

# description: name of vault to import into
# type: string
# required: true
vaultName: vault

# description: whether to concatenate everything into one note
# type: boolean
# concatenate: TODO

# description: frontmatter to add to each note
# type: object
# frontmatter: TODO

# description: use the file name as the id
# type: boolean
# fnameAsId: TODO

# description: If concatenate is set, name of destination path
# type: string
# destName: TODO

# description: owner of the repository
# type: string
# required: true
owner: imba

# description: github repository to import from
# type: string
# required: true
repository: imba.io

# description: status of issue open/closed
# type: string
# required: true
status: open

# description: import issues created before this date: YYYY-MM-DD
# type: string
# endDate: 2022-03-09

# description: import issues created after this date: YYYY-MM-DD
# type: string
# startDate: TODO

# description: github personal access token
# type: string
# required: true
token:

# description: name of hierarchy to import into
# type: string
# required: true
fname: issues.open
